// TurboQuant1.5 CUDA flash attention vec kernel instantiation

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TURBO1_5, GGML_TYPE_TURBO1_5);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TURBO1_5, GGML_TYPE_TURBO1_5);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TURBO1_5, GGML_TYPE_TURBO1_5);
