#!/usr/bin/env sh

printf "# date: %s\n" "$(date)" > AUTHORS
printf "# this file is auto-generated by scripts/gen-authors.sh\n\n" >> AUTHORS

git log --format='%an <%ae>' --reverse --date=short master | awk '!seen[$0]++' | sort >> AUTHORS

# if necessary, update your name here. for example: jdoe -> John Doe
sed 's/^jdoe/John Doe/g' AUTHORS > AUTHORS.tmp && mv AUTHORS.tmp AUTHORS
